name: Django CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Backend/WhatMunch_Django/requirements.txt
        
    - name: Set Environment Variables for Tests
      run: |
        echo "DJANGO_SETTINGS_MODULE=WhatMunch_Django.settings.test" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV
        
    - name: Run Migrations & Tests
      run: |
        python Backend/WhatMunch_Django/manage.py migrate
        cd ./Backend/WhatMunch_Django/
        pytest
        
    - name: Set Environment Variables for Deployment
      if: success()
      run: |
        echo "DJANGO_SETTINGS_MODULE=WhatMunch_Django.settings.prod" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.PROD_DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.PROD_DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.PROD_DB_HOST }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.PROD_DB_PORT }}" >> $GITHUB_ENV
    
