name: build and test .NET MAUI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Mobile/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Mobile/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore Mobile/WhatMunch_MAUI/WhatMunch_MAUI.sln

    # Build Android
    - name: Build Android
      run: dotnet build Mobile/WhatMunch_MAUI/WhatMunch_MAUI.csproj -f net9.0-android --configuration Release --no-restore

    # Build Windows
    - name: Build Windows
      run: dotnet build ./MAUI/MAUI.csproj -f net9.0-windows10.0.19041.0 -p:RuntimeIdentifierOverride=win10-x64 --configuration Release

    - name: Test
      run: dotnet test Mobile/WhatMunch_MAUI.Tests/WhatMunch_MAUI.Tests.csproj --no-build --verbosity normal
