name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI workloads
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore Mobile/WhatMunch_MAUI/WhatMunch_MAUI.sln

    - name: Build
      run: dotnet build Mobile/WhatMunch_MAUI/WhatMunch_MAUI.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Mobile/WhatMunch_MAUI/WhatMunch_MAUI.sln --no-build --verbosity normal
