name: Build MAUI Android App

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build-android:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install .NET MAUI Workloads
      run: dotnet workload restore

    - name: Restore dependencies
      run: dotnet restore Mobile/WhatMunch_MAUI/WhatMunch_MAUI.csproj

    - name: Build (Android)
      run: dotnet build Mobile/WhatMunch_MAUI/WhatMunch_MAUI.csproj -c Release --no-restore
